# Generated by Django 5.0.3 on 2024-03-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tonnes_trucked', models.FloatField()),
                ('tonnes_hoisted', models.FloatField()),
                ('tonnes_trammed', models.FloatField()),
                ('meters_drilled', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tonnes_blasted', models.FloatField()),
                ('downtime', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
