# Generated by Django 5.0.3 on 2024-04-02 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_pit_tonnage', models.FloatField()),
                ('cymric_tonnage', models.FloatField()),
                ('cymric_day', models.FloatField()),
                ('cymric_night', models.FloatField()),
                ('bottom_section_total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='prod_downtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('downtime', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mine_section', to='production.sections')),
            ],
        ),
    ]
