# Generated by Django 5.0.3 on 2024-04-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_production_data_sections_prod_downtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='budgets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('trucked', models.FloatField()),
                ('hoisted', models.FloatField()),
                ('gold', models.FloatField()),
                ('grade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('drilling', models.FloatField()),
                ('blasting', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='summaries',
            name='grade',
            field=models.DecimalField(decimal_places=2, default=2.1, max_digits=10),
            preserve_default=False,
        ),
    ]
