# Generated by Django 5.0.3 on 2024-04-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_budgets_summaries_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='production_data',
            name='milled_tonnage',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='production_data',
            name='trucked_tonnage',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
