# Generated by Django 5.0.3 on 2024-04-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_production_data_milled_tonnage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaries',
            name='gold',
            field=models.DecimalField(decimal_places=2, default=2.2, max_digits=10),
            preserve_default=False,
        ),
    ]
