# Generated by Django 5.0.3 on 2024-04-22 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_summaries_gold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summaries',
            name='tonnes_trammed',
        ),
    ]
