# Generated by Django 5.0.3 on 2024-04-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_remove_summaries_tonnes_trammed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ug_tonnes', models.FloatField()),
                ('op_tonnes', models.FloatField()),
                ('milled_tonnes', models.FloatField()),
                ('dev_drilling', models.FloatField()),
                ('ore_gen', models.FloatField()),
                ('grade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dowmtime', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fatality', models.IntegerField()),
                ('lti', models.IntegerField()),
                ('nlti', models.IntegerField()),
            ],
        ),
    ]
