# Generated by Django 4.1.5 on 2024-04-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_data_cil_feed_grade_data_reconciled_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('c1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('c2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('c3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('c1_cash_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('c2_cash_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('c3_cash_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='FatalityFreeShifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('shifts', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='production_data',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='safetyperformance',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
