# Generated by Django 4.1.5 on 2024-04-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_costs_fatalityfreeshifts_alter_data_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='trammings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('western_top', models.FloatField()),
                ('cymric_top', models.FloatField()),
                ('cymric_bottom', models.FloatField()),
                ('l_13', models.FloatField()),
                ('l_15', models.FloatField()),
                ('far_east', models.FloatField()),
            ],
        ),
    ]
