# Generated by Django 4.1.5 on 2024-05-08 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_trammings'),
    ]

    operations = [
        migrations.AddField(
            model_name='trammings',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 8, 12, 36, 57, 978043, tzinfo=datetime.timezone.utc), unique=True),
            preserve_default=False,
        ),
    ]
