# Generated by Django 4.1.5 on 2024-05-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='gold_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
