# Generated by Django 4.1.5 on 2024-05-09 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_cost_gold_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='gold_price',
        ),
    ]
