# Generated by Django 4.1.5 on 2024-05-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_goldprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='gold',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
