# Generated by Django 4.1.5 on 2024-05-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0018_trammings_cymric_bottom_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costs',
            name='gold_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
