# Generated by Django 4.1.5 on 2024-05-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0019_costs_gold_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='fin_cost_budgets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('mining', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mine_engineering', models.DecimalField(decimal_places=2, max_digits=10)),
                ('processing', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hauling', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tsd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owners', models.DecimalField(decimal_places=2, max_digits=10)),
                ('open_pit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depreciation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('c3_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('c1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('c2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('c3', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='fin_costs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('mining', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mine_engineering', models.DecimalField(decimal_places=2, max_digits=10)),
                ('processing', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hauling', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tsd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owners', models.DecimalField(decimal_places=2, max_digits=10)),
                ('open_pit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depreciation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('c3_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('c1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('c2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('c3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gold_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='cost',
            name='gold_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
