# Generated by Django 4.1.5 on 2024-06-20 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0020_fin_cost_budgets_fin_costs_cost_gold_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('head', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='fin_budgets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('utilities', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stores', models.DecimalField(decimal_places=2, max_digits=10)),
                ('repairs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hauling', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('processing', models.DecimalField(decimal_places=2, max_digits=10)),
                ('open_pit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('social_ammenities', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_overheads', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imtt', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='prod_udget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Costs_centers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_id', models.CharField(max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_cost_center', to='production.departments')),
            ],
        ),
    ]
