# Generated by Django 4.1.5 on 2024-06-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0021_departments_fin_budgets_prod_udget_costs_centers'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_budgets',
            name='date',
            field=models.DateField(default='2024-01-01', unique=True),
            preserve_default=False,
        ),
    ]
