# Generated by Django 4.1.5 on 2024-06-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0025_dept_spending_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept_spending',
            name='date',
            field=models.DateField(),
        ),
    ]
