# Generated by Django 4.1.5 on 2024-06-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0026_alter_dept_spending_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept_spending_plan',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fin_budgets',
            name='date',
            field=models.DateField(),
        ),
    ]
