# Generated by Django 5.0.7 on 2024-07-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0027_alter_dept_spending_plan_date_alter_fin_budgets_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='prod_budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('rom', models.FloatField()),
                ('milled_tonnes', models.FloatField()),
                ('gold', models.FloatField()),
                ('grade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dev_drilling', models.FloatField()),
                ('ore_gen', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='prod_udget',
        ),
    ]
