# Generated by Django 5.0.7 on 2024-08-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0028_prod_budget_delete_prod_udget'),
    ]

    operations = [
        migrations.CreateModel(
            name='budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('rom', models.FloatField()),
                ('milled_tonnes', models.FloatField()),
                ('gold', models.FloatField()),
                ('grade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dev_drilling', models.FloatField()),
                ('ore_gen', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='cash_costs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('c1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('c2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('c3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gold_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
