# Generated by Django 5.0.7 on 2024-08-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0029_budget_cash_costs'),
    ]

    operations = [
        migrations.CreateModel(
            name='gold_estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('cil', models.DecimalField(decimal_places=4, max_digits=10)),
                ('scats', models.DecimalField(decimal_places=4, max_digits=10)),
                ('grg', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
    ]
