# Generated by Django 5.0.7 on 2024-09-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0030_gold_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='recovery_perc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
