# Generated by Django 5.0.7 on 2024-09-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0031_data_recovery_perc'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='recovery',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='recovery',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prod_budget',
            name='recovery',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
