# Generated by Django 5.0.7 on 2024-10-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0033_data_stock_pile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engineering_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('zesa_downtime', models.FloatField()),
            ],
        ),
    ]
