# Generated by Django 5.0.7 on 2024-10-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0034_engineering_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
