# Generated by Django 5.0.7 on 2024-10-25 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0035_alter_data_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='dowmtime',
        ),
    ]
